name: learn-github-actions
on: 
  workflow_dispatch:
    inputs:
      
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: build project
        run: make  
